"use client";
import Link from "next/link";
import {useActionState} from "react";
import {useFormStatus} from "react-dom";
import {deleteCollectionDraft, deletePlatformCollection, publishCollectionDraft, saveCollectionDraft, type AdminContentState} from "@/app/[locale]/admin/collections/actions";
import type {CatalogSkillOption, CollectionDraft, PlatformCollectionAdmin} from "@/lib/admin/content";
const idle:AdminContentState={status:"idle"};
function Button({children,tone="primary"}:{children:React.ReactNode;tone?:"primary"|"danger"}){const{pending}=useFormStatus();return <button disabled={pending} className={tone==="primary"?"btn-payment min-h-10 rounded-xl px-4 text-sm font-semibold":"min-h-10 rounded-xl border border-error/40 px-4 text-sm font-semibold text-error"}>{pending?"…":children}</button>}
export default function AdminCollectionEditor({locale,skills,draft,collection}:{locale:string;skills:CatalogSkillOption[];draft?:CollectionDraft;collection?:PlatformCollectionAdmin}){
 const [save,saveAction]=useActionState(saveCollectionDraft,idle);const[pub,pubAction]=useActionState(publishCollectionDraft,idle);const[del,delAction]=useActionState(draft?deleteCollectionDraft:deletePlatformCollection,idle);const selected=new Set(draft?.skill_ids??collection?.skill_ids??[]);const input="mt-2 min-h-11 w-full rounded-xl border border-outline-variant/50 bg-background/65 px-3 py-2 text-sm outline-none focus:border-primary";
 return <article className="rounded-3xl border border-outline-variant/45 bg-surface-container-low/55 p-5 sm:p-7"><div className="mb-5 flex items-center justify-between gap-3"><h2 className="font-geist text-xl font-bold">{draft?.slug??collection?.slug??(locale==="vi"?"Bộ sưu tập mới":"New collection")}</h2>{draft&&<span className="rounded-full bg-secondary/12 px-3 py-1 text-xs text-secondary">{locale==="vi"?"Bản nháp":"Draft"}</span>}</div>
 <form action={saveAction} className="space-y-4"><input type="hidden" name="draftId" value={draft?.id??""}/><input type="hidden" name="collectionId" value={draft?.collection_id??collection?.id??""}/><label className="text-xs font-semibold">Slug<input name="slug" required defaultValue={draft?.slug??collection?.slug??""} className={input}/></label><div className="grid gap-4 md:grid-cols-2"><label className="text-xs font-semibold">Name EN<input name="nameEn" required defaultValue={draft?.name_en??collection?.name??""} className={input}/></label><label className="text-xs font-semibold">Tên VI<input name="nameVi" required defaultValue={draft?.name_vi??collection?.name??""} className={input}/></label><label className="text-xs font-semibold">Description EN<textarea name="descriptionEn" defaultValue={draft?.description_en??collection?.description??""} rows={3} className={input}/></label><label className="text-xs font-semibold">Mô tả VI<textarea name="descriptionVi" defaultValue={draft?.description_vi??collection?.description??""} rows={3} className={input}/></label></div><label className="text-xs font-semibold">Accent<select name="accent" defaultValue={draft?.accent??collection?.accent??"primary"} className={input}><option>primary</option><option>secondary</option><option>tertiary</option></select></label><fieldset><legend className="text-xs font-semibold">Skills</legend><div className="mt-2 grid max-h-72 gap-2 overflow-y-auto rounded-xl border border-outline-variant/40 p-3 sm:grid-cols-2">{skills.map(s=><label key={s.id} className="flex gap-2 text-xs"><input type="checkbox" name="skillIds" value={s.id} defaultChecked={selected.has(s.id)} className="accent-primary"/><span>{s.title} <span className="text-on-surface-variant">({s.slug})</span></span></label>)}</div></fieldset>{save.status!=="idle"&&<p className={save.status==="success"?"text-sm text-tertiary":"text-sm text-error"}>{save.status==="success"?(locale==="vi"?"Đã lưu bản nháp.":"Draft saved."):save.message}</p>}<div className="flex justify-end"><Button>{draft?(locale==="vi"?"Lưu chỉnh sửa":"Save changes"):(locale==="vi"?"Lưu bản nháp":"Save draft")}</Button></div></form>
 {(draft||collection)&&<div className="mt-4 flex flex-wrap items-center gap-3 border-t border-outline-variant/35 pt-4">{draft&&<><Link href={`/${locale}/admin/collections/${draft.id}/preview`} className="min-h-10 rounded-xl border border-primary/40 px-4 py-2 text-sm font-semibold text-primary">{locale==="vi"?"Xem trước":"Preview"}</Link><form action={pubAction}><input type="hidden" name="draftId" value={draft.id}/><Button>{locale==="vi"?"Đăng bộ sưu tập":"Publish collection"}</Button></form></>}<form action={delAction} className="ml-auto"><input type="hidden" name={draft?"draftId":"collectionId"} value={draft?.id??collection?.id}/><Button tone="danger">{locale==="vi"?"Xóa":"Delete"}</Button></form>{(pub.status==="error"||del.status==="error")&&<p className="w-full text-sm text-error">{pub.message??del.message}</p>}</div>}</article>;
}
