"use server";
import {revalidatePath} from "next/cache";
import {getLocale} from "next-intl/server";
import {requirePlatformAdmin} from "@/lib/admin/auth";
import {createAdminClient} from "@/lib/supabase/admin";
export type AdminContentState={status:"idle"|"success"|"error";message?:string};
const uuid=/^[0-9a-f]{8}-[0-9a-f-]{27}$/i; const slug=/^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const clean=(v:FormDataEntryValue|null)=>typeof v==="string"?v.trim():"";
const error=(e:unknown):AdminContentState=>({status:"error",message:e instanceof Error?e.message:"operation_failed"});
export async function saveCollectionDraft(_p:AdminContentState,fd:FormData):Promise<AdminContentState>{try{const actor=await requirePlatformAdmin();const id=clean(fd.get("draftId"));const collectionId=clean(fd.get("collectionId"));const data={collection_id:collectionId||null,slug:clean(fd.get("slug")),name_en:clean(fd.get("nameEn")),name_vi:clean(fd.get("nameVi")),description_en:clean(fd.get("descriptionEn")),description_vi:clean(fd.get("descriptionVi")),accent:clean(fd.get("accent")),skill_ids:fd.getAll("skillIds").map(String),created_by:actor.id,status:"review"};if(!slug.test(data.slug)||!data.name_en||!data.name_vi||!data.skill_ids.length)throw new Error("invalid_collection");const admin=createAdminClient();const result=id?await admin.from("platform_collection_drafts").update(data).eq("id",id).eq("status","review"):await admin.from("platform_collection_drafts").insert(data);if(result.error)throw result.error;revalidatePath(`/${await getLocale()}/admin/collections`);return{status:"success",message:"saved"};}catch(e){return error(e)}}
export async function beginCollectionEdit(_p:AdminContentState,fd:FormData):Promise<AdminContentState>{try{const actor=await requirePlatformAdmin();const id=clean(fd.get("collectionId"));if(!uuid.test(id))throw new Error("invalid_id");const admin=createAdminClient();const {data:c,error:e}=await admin.from("skill_collections").select("id,slug,name,description,accent,skill_collection_items(skill_id,position),skill_collection_translations(locale,name,description)").eq("id",id).eq("collection_type","platform").single();if(e)throw e;const tr=c.skill_collection_translations??[];const en=tr.find((x)=>x.locale==="en"),vi=tr.find((x)=>x.locale==="vi");const {error:insertError}=await admin.from("platform_collection_drafts").insert({collection_id:c.id,slug:c.slug,name_en:en?.name??c.name,name_vi:vi?.name??c.name,description_en:en?.description??c.description,description_vi:vi?.description??c.description,accent:c.accent,skill_ids:[...(c.skill_collection_items??[])].sort((a,b)=>a.position-b.position).map(x=>x.skill_id),created_by:actor.id});if(insertError)throw insertError;revalidatePath(`/${await getLocale()}/admin/collections`);return{status:"success"};}catch(e){return error(e)}}
export async function publishCollectionDraft(_p:AdminContentState,fd:FormData):Promise<AdminContentState>{try{const actor=await requirePlatformAdmin();const id=clean(fd.get("draftId"));if(!uuid.test(id))throw new Error("invalid_id");const {error:e}=await createAdminClient().rpc("publish_platform_collection_draft",{p_draft_id:id,p_actor_id:actor.id});if(e)throw e;const locale=await getLocale();revalidatePath(`/${locale}/admin/collections`);revalidatePath(`/${locale}/skills`,`layout`);return{status:"success"};}catch(e){return error(e)}}
export async function deleteCollectionDraft(_p:AdminContentState,fd:FormData):Promise<AdminContentState>{try{await requirePlatformAdmin();const id=clean(fd.get("draftId"));const {error:e}=await createAdminClient().from("platform_collection_drafts").delete().eq("id",id).eq("status","review");if(e)throw e;revalidatePath(`/${await getLocale()}/admin/collections`);return{status:"success"};}catch(e){return error(e)}}
export async function deletePlatformCollection(_p:AdminContentState,fd:FormData):Promise<AdminContentState>{try{await requirePlatformAdmin();const id=clean(fd.get("collectionId"));const {error:e}=await createAdminClient().from("skill_collections").delete().eq("id",id).eq("collection_type","platform");if(e)throw e;const locale=await getLocale();revalidatePath(`/${locale}/admin/collections`);revalidatePath(`/${locale}/skills`,`layout`);return{status:"success"};}catch(e){return error(e)}}
