"use server";
import {revalidatePath} from "next/cache";
import {getLocale} from "next-intl/server";
import {requirePlatformAdmin} from "@/lib/admin/auth";
import {createAdminClient} from "@/lib/supabase/admin";
import type {AdminContentState} from "../collections/actions";
const slug=/^[a-z0-9]+(?:-[a-z0-9]+)*$/; const clean=(v:FormDataEntryValue|null)=>typeof v==="string"?v.trim():""; const fail=(e:unknown):AdminContentState=>({status:"error",message:e instanceof Error?e.message:"operation_failed"});
export async function saveBlogDraft(_p:AdminContentState,fd:FormData):Promise<AdminContentState>{try{const actor=await requirePlatformAdmin();const id=clean(fd.get("draftId"));const data={published_slug:clean(fd.get("publishedSlug"))||null,slug:clean(fd.get("slug")),title_en:clean(fd.get("titleEn")),title_vi:clean(fd.get("titleVi")),excerpt_en:clean(fd.get("excerptEn")),excerpt_vi:clean(fd.get("excerptVi")),content_en:clean(fd.get("contentEn")),content_vi:clean(fd.get("contentVi")),category:clean(fd.get("category"))||"Guide",author_name:clean(fd.get("authorName"))||"OceanSkill",icon:clean(fd.get("icon"))||"article",reading_minutes:Number(clean(fd.get("readingMinutes"))||5),created_by:actor.id,status:"review"};if(!slug.test(data.slug)||!data.title_en||!data.title_vi||!data.content_en||!data.content_vi)throw new Error("invalid_blog_post");const admin=createAdminClient();const result=id?await admin.from("blog_post_drafts").update(data).eq("id",id).eq("status","review"):await admin.from("blog_post_drafts").insert(data);if(result.error)throw result.error;revalidatePath(`/${await getLocale()}/admin/blog`);return{status:"success"};}catch(e){return fail(e)}}
export async function publishBlogDraft(_p:AdminContentState,fd:FormData):Promise<AdminContentState>{try{const actor=await requirePlatformAdmin();const id=clean(fd.get("draftId"));const {error:e}=await createAdminClient().rpc("publish_blog_post_draft",{p_draft_id:id,p_actor_id:actor.id});if(e)throw e;const locale=await getLocale();revalidatePath(`/${locale}/admin/blog`);revalidatePath(`/${locale}/blog`);return{status:"success"};}catch(e){return fail(e)}}
export async function deleteBlogDraft(_p:AdminContentState,fd:FormData):Promise<AdminContentState>{try{await requirePlatformAdmin();const {error:e}=await createAdminClient().from("blog_post_drafts").delete().eq("id",clean(fd.get("draftId"))).eq("status","review");if(e)throw e;revalidatePath(`/${await getLocale()}/admin/blog`);return{status:"success"};}catch(e){return fail(e)}}
export async function deletePublishedBlog(_p:AdminContentState,fd:FormData):Promise<AdminContentState>{try{await requirePlatformAdmin();const target=clean(fd.get("slug"));const {error:e}=await createAdminClient().from("blog_posts").delete().eq("slug",target);if(e)throw e;const locale=await getLocale();revalidatePath(`/${locale}/admin/blog`);revalidatePath(`/${locale}/blog`);return{status:"success"};}catch(e){return fail(e)}}
